export const SET_LIST = 'SET_LIST'
export const SET_LOADING = 'SET_LOADING'
export const MOVE_ITEM = 'MOVE_ITEM'
export const MOVE_BACK = 'MOVE_BACK'
export const SORT_LIST = 'SORT_LIST'
export const SAVE_ORIGINAL_LIST = 'SAVE_ORIGINAL_LIST'
export const SET_QUERY = 'SET_QUERY'

export const ADD_EVENT = 'ADD_EVENT'
export const REMOVE_EVENT = 'REMOVE_EVENT'
